/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"
#include "JSTestDictionaryLegacyNativeDictionaryRequiredInterfaceNullability.h"

#include "JSDOMConvertInterface.h"
#include "JSDOMGlobalObject.h"
#include "JSNode.h"
#include <JavaScriptCore/JSCInlines.h>
#include <JavaScriptCore/ObjectConstructor.h>



namespace WebCore {
using namespace JSC;

template<> ConversionResult<IDLDictionary<TestDictionaryLegacyNativeDictionaryRequiredInterfaceNullability>> convertDictionary<TestDictionaryLegacyNativeDictionaryRequiredInterfaceNullability>(JSGlobalObject& lexicalGlobalObject, JSValue value)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);
    bool isNullOrUndefined = value.isUndefinedOrNull();
    auto* object = isNullOrUndefined ? nullptr : value.getObject();
    if (!isNullOrUndefined && !object) [[unlikely]] {
        throwTypeError(&lexicalGlobalObject, throwScope);
        return ConversionResultException { };
    }
    TestDictionaryLegacyNativeDictionaryRequiredInterfaceNullability result;
    JSValue optionalInterfaceMemberValue;
    if (isNullOrUndefined)
        optionalInterfaceMemberValue = jsUndefined();
    else {
        optionalInterfaceMemberValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "optionalInterfaceMember"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    if (!optionalInterfaceMemberValue.isUndefined()) {
        auto optionalInterfaceMemberConversionResult = convert<IDLInterface<Node>>(lexicalGlobalObject, optionalInterfaceMemberValue);
        if (optionalInterfaceMemberConversionResult.hasException(throwScope)) [[unlikely]]
            return ConversionResultException { };
        result.optionalInterfaceMember = optionalInterfaceMemberConversionResult.releaseReturnValue();
    }
    JSValue requiredInterfaceMemberValue;
    if (isNullOrUndefined)
        requiredInterfaceMemberValue = jsUndefined();
    else {
        requiredInterfaceMemberValue = object->get(&lexicalGlobalObject, Identifier::fromString(vm, "requiredInterfaceMember"_s));
        RETURN_IF_EXCEPTION(throwScope, ConversionResultException { });
    }
    if (requiredInterfaceMemberValue.isUndefined()) {
        throwRequiredMemberTypeError(lexicalGlobalObject, throwScope, "requiredInterfaceMember"_s, "TestDictionaryLegacyNativeDictionaryRequiredInterfaceNullability"_s, "Node"_s);
        return ConversionResultException { };
    }
    auto requiredInterfaceMemberConversionResult = convert<IDLInterface<Node>>(lexicalGlobalObject, requiredInterfaceMemberValue);
    if (requiredInterfaceMemberConversionResult.hasException(throwScope)) [[unlikely]]
        return ConversionResultException { };
    result.requiredInterfaceMember = requiredInterfaceMemberConversionResult.releaseReturnValue();
    return result;
}

JSC::JSObject* convertDictionaryToJS(JSC::JSGlobalObject& lexicalGlobalObject, JSDOMGlobalObject& globalObject, const TestDictionaryLegacyNativeDictionaryRequiredInterfaceNullability& dictionary)
{
    SUPPRESS_UNCOUNTED_LOCAL auto& vm = JSC::getVM(&lexicalGlobalObject);
    auto throwScope = DECLARE_THROW_SCOPE(vm);

    auto result = constructEmptyObject(&lexicalGlobalObject, globalObject.objectPrototype());

    if (!IDLInterface<Node>::isNullValue(dictionary.optionalInterfaceMember)) {
        auto optionalInterfaceMemberValue = toJS<IDLInterface<Node>>(lexicalGlobalObject, globalObject, throwScope, IDLInterface<Node>::extractValueFromNullable(dictionary.optionalInterfaceMember));
        RETURN_IF_EXCEPTION(throwScope, { });
        result->putDirect(vm, JSC::Identifier::fromString(vm, "optionalInterfaceMember"_s), optionalInterfaceMemberValue);
    }
    auto requiredInterfaceMemberValue = toJS<IDLNullable<IDLInterface<Node>>>(lexicalGlobalObject, globalObject, throwScope, dictionary.requiredInterfaceMember);
    RETURN_IF_EXCEPTION(throwScope, { });
    result->putDirect(vm, JSC::Identifier::fromString(vm, "requiredInterfaceMember"_s), requiredInterfaceMemberValue);
    return result;
}

} // namespace WebCore

