set(PORT MorphOS)
find_package(Threads REQUIRED)

cmake_policy(SET CMP0074 NEW)

WEBKIT_OPTION_BEGIN()

WEBKIT_OPTION_DEFINE(USE_LIBHYPHEN "" PUBLIC ON)

# Marking text and co
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_DRAG_SUPPORT PRIVATE ON)

# Filtering, JS injections and other crap
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_CONTENT_EXTENSIONS PRIVATE ON)

### Things that'll stay off:
# Payment things
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_APPLE_PAY PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_APPLE_PAY_SESSION_V3 PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_APPLE_PAY_SESSION_V4 PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_PAYMENT_REQUEST PRIVATE OFF)
# WebGL
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WEBGL PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WEBGL2 PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WEBGPU PRIVATE OFF)

#### MorphOS TODO
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_NOTIFICATIONS PRIVATE OFF)
# port bmalloc
WEBKIT_OPTION_DEFAULT_PORT_VALUE(USE_SYSTEM_MALLOC PRIVATE ON)
# gstreamer/custom impl
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WEB_AUDIO PRIVATE OFF)
# impl class
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_SMOOTH_SCROLLING PRIVATE OFF)
# investigate
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_REMOTE_INSPECTOR PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_RESOURCE_USAGE PRIVATE OFF)

### Not happening
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_FTL_JIT PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_ACCESSIBILITY PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_GEOLOCATION PRIVATE OFF)
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_3D_TRANSFORMS PRIVATE OFF)

WEBKIT_OPTION_END()

find_package(Cairo REQUIRED)
find_package(Freetype REQUIRED)
find_package(CURL 7.60.0 REQUIRED)
find_package(ICU REQUIRED COMPONENTS uc i18n data)
find_package(HarfBuzz REQUIRED COMPONENTS ICU)
find_package(JPEG 1.5.2 REQUIRED)
find_package(LibXml2 2.9.7 REQUIRED)
find_package(OpenSSL 1.1.1 REQUIRED)
find_package(ZLIB 1.2.11 REQUIRED)
find_package(PNG REQUIRED)
find_package(Sqlite 3.23.1 REQUIRED)
find_package(Nghttp2 REQUIRED)
find_package(Hyphen REQUIRED)
find_package(LibPSL REQUIRED)
find_package(LibGcrypt 1.6.0 REQUIRED)
find_package(LibXslt 1.1.32 REQUIRED)
find_package(Libtasn1 REQUIRED)
find_package(WebP 1.0.0 REQUIRED)

SET_AND_EXPOSE_TO_BUILD(USE_CAIRO ON)
SET_AND_EXPOSE_TO_BUILD(USE_CURL ON)
SET_AND_EXPOSE_TO_BUILD(USE_FREETYPE ON)
SET_AND_EXPOSE_TO_BUILD(USE_HARFBUZZ ON)
SET_AND_EXPOSE_TO_BUILD(USE_EXPORT_MACROS ON)
SET_AND_EXPOSE_TO_BUILD(USE_INSPECTOR_SOCKET_SERVER ${ENABLE_REMOTE_INSPECTOR})
SET_AND_EXPOSE_TO_BUILD(USE_LD_GOLD OFF)
SET_AND_EXPOSE_TO_BUILD(USE_GCRYPT TRUE)


###
#SET_AND_EXPOSE_TO_BUILD(ENABLE_GRAPHICS_CONTEXT_3D OFF)
#SET_AND_EXPOSE_TO_BUILD(USE_COORDINATED_GRAPHICS ON)
#SET_AND_EXPOSE_TO_BUILD(USE_EGL OFF)
#SET_AND_EXPOSE_TO_BUILD(USE_NICOSIA TRUE)
#SET_AND_EXPOSE_TO_BUILD(USE_OPENGL_ES OFF)
#SET_AND_EXPOSE_TO_BUILD(USE_TEXTURE_MAPPER ON)
#SET_AND_EXPOSE_TO_BUILD(USE_TEXTURE_MAPPER_GL OFF)
#SET_AND_EXPOSE_TO_BUILD(USE_TILED_BACKING_STORE ON)
###



set(WTF_LIBRARY_TYPE STATIC)
set(JavaScriptCore_LIBRARY_TYPE STATIC)
set(WebCore_LIBRARY_TYPE STATIC)
set(WebKitLegacy_LIBRARY_TYPE STATIC)

set(ENABLE_API_TESTS OFF)
set(ENABLE_WEBCORE ON)
set(ENABLE_WEBKIT OFF)
set(ENABLE_WEBKIT_LEGACY ON)
set(ENABLE_GRAPHICS_CONTEXT_3D OFF)

#set(JAVASCRIPTCORE_DIR "${CMAKE_SOURCE_DIR}/JavaScriptCore")
#set(WTF_DIR "${CMAKE_SOURCE_DIR}"/WTF)

# Override headers directories
#set(WTF_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/WTF/Headers)
#set(JavaScriptCore_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/JavaScriptCore/Headers)
#set(JavaScriptCore_PRIVATE_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/JavaScriptCore/PrivateHeaders)

# Override derived sources directories
#set(WTF_DERIVED_SOURCES_DIR ${CMAKE_BINARY_DIR}/WTF/DerivedSources)
#set(JavaScriptCore_DERIVED_SOURCES_DIR ${CMAKE_BINARY_DIR}/JavaScriptCore/DerivedSources)

# Override scripts directories
#set(WTF_SCRIPTS_DIR ${CMAKE_BINARY_DIR}/WTF/Scripts)
#set(JavaScriptCore_SCRIPTS_DIR ${CMAKE_BINARY_DIR}/JavaScriptCore/Scripts)

